version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-local
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_WEBHOOK_BASE_URL=http://localhost:5678/
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_HIRING_BANNER_ENABLED=false
      - N8N_TEMPLATES_ENABLED=true
      - N8N_METRICS=false
      - GENERIC_TIMEZONE=America/Los_Angeles
    volumes:
      - ./n8n-data:/home/node/.n8n
      - ./workflows:/home/node/workflows
    networks:
      - n8n-network
    restart: unless-stopped

networks:
  n8n-network:
    driver: bridge

volumes:
  n8n-data:
    driver: local