[build]
builder = "NIXPACKS"

[deploy]
startCommand = "n8n start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/healthz"
healthcheckTimeout = 300

[variables]
# Railway Service Configuration
PORT = "5678"
N8N_HOST = "0.0.0.0"
N8N_PORT = "5678"
N8N_PROTOCOL = "https"
NODE_ENV = "production"

# Database Configuration
DB_TYPE = "postgresdb"
DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED = "false"
DB_POSTGRESDB_SSL_CA = ""
DB_POSTGRESDB_SSL_CERT = ""
DB_POSTGRESDB_SSL_KEY = ""

# n8n Configuration
N8N_BASIC_AUTH_ACTIVE = "false"
N8N_DIAGNOSTICS_ENABLED = "false"
N8N_VERSION_NOTIFICATIONS_ENABLED = "false"
N8N_HIRING_BANNER_ENABLED = "false"
N8N_TEMPLATES_ENABLED = "true"
N8N_METRICS = "false"
GENERIC_TIMEZONE = "America/Los_Angeles"

# Logging and Debug
N8N_LOG_LEVEL = "info"
N8N_LOG_OUTPUT = "console"

[[services]]
name = "n8n"