[build]
builder = "NIXPACKS"

[deploy]
startCommand = "n8n start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
N8N_HOST = "0.0.0.0"
N8N_PORT = "5678"
PORT = "5678"
N8N_PROTOCOL = "https"
WEBHOOK_URL = "${RAILWAY_PUBLIC_DOMAIN}"
N8N_EDITOR_BASE_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"
N8N_METRICS = "false"
N8N_DIAGNOSTICS_ENABLED = "false"
EXECUTIONS_PROCESS = "main"
N8N_LOG_LEVEL = "info"
N8N_VERSION_NOTIFICATIONS_ENABLED = "false"
N8N_HIRING_BANNER_ENABLED = "false"
GENERIC_TIMEZONE = "UTC"
NODE_ENV = "production"
N8N_BASIC_AUTH_ACTIVE = "false"
N8N_SECURE_COOKIE = "false"
N8N_PROXY_HOPS = "1"
DB_TYPE = "postgresdb"
DB_POSTGRESDB_DATABASE = "${PGDATABASE}"
DB_POSTGRESDB_HOST = "${PGHOST}"
DB_POSTGRESDB_PORT = "${PGPORT}"
DB_POSTGRESDB_USER = "${PGUSER}"
DB_POSTGRESDB_PASSWORD = "${PGPASSWORD}"

[[services]]
name = "n8n"