[build]
builder = "NIXPACKS"

[deploy]
startCommand = "n8n start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
N8N_HOST = "0.0.0.0"
N8N_PORT = "5678"
N8N_PROTOCOL = "https"
N8N_METRICS = "false"
N8N_DIAGNOSTICS_ENABLED = "false"
EXECUTIONS_PROCESS = "main"
N8N_LOG_LEVEL = "info"
N8N_VERSION_NOTIFICATIONS_ENABLED = "false"
N8N_HIRING_BANNER_ENABLED = "false"
GENERIC_TIMEZONE = "UTC"
NODE_ENV = "production"

[[services]]
name = "n8n"